### ISSUE TITLE
Logging level for method entry should be TRACE, not INFO

### ISSUE THREAD

**Issue by suryakiranl** [sainimmetry/PythonDI#1]
https://github.com/sainimmetry/PythonDI/blob/74ef2b80c1f2da4b36e4cbde656382f8979af2ad/NimmetryDI/com/nimmetry/di/LoadListData.py#L13

**Comment by sainimmetry** [comment]
Trace is not available in the python version. Closing the issue

https://bugs.python.org/issue31732

FYR
