### ISSUE TITLE
None of the methods in this class should be static. They should all be object level methods.

### ISSUE THREAD

**Issue by suryakiranl** [sainimmetry/PythonDI#10]
https://github.com/sainimmetry/PythonDI/blob/74ef2b80c1f2da4b36e4cbde656382f8979af2ad/NimmetryDI/com/nimmetry/di/LoadListData.py#L33

* Our usage pattern instantiates an object with username, password and API URL to go through the program execution.
* And all the methods use these attributes to further make progress in the code.

So it is ideal to make these object level methods and not Class level static methods.

**Comment by sainimmetry** [comment]
Noted and removed static annotation from code. Committed the file
