### ISSUE TITLE
Code reuse / modularization is needed

### ISSUE THREAD

**Issue by suryakiranl** [sainimmetry/PythonDI#11]
https://github.com/sainimmetry/PythonDI/blob/74ef2b80c1f2da4b36e4cbde656382f8979af2ad/NimmetryDI/com/nimmetry/di/LoadListData.py#L63

As we will be generating the Access Token object more than once, please modularize it into a function so that there is no code duplication.

**Comment by sainimmetry** [comment]
access_domain_token = {'x-access-token': access_token} 
is moved to Requesthandler.py
