### ISSUE TITLE
Please declare and use constants for any static strings in the code

### ISSUE THREAD

**Issue by suryakiranl** [sainimmetry/PythonDI#6]
https://github.com/sainimmetry/PythonDI/blob/74ef2b80c1f2da4b36e4cbde656382f8979af2ad/NimmetryDI/com/nimmetry/di/LoadListData.py#L39

This makes code very maintainable. And we exactly know upfront what are the constant strings we use in each class.

**Comment by sainimmetry** [comment]
Delcared constant values to a seperate file Constants.py
