### ISSUE TITLE
Do not return value from a function if the caller does not use it

### ISSUE THREAD

**Issue by suryakiranl** [sainimmetry/PythonDI#7]
https://github.com/sainimmetry/PythonDI/blob/74ef2b80c1f2da4b36e4cbde656382f8979af2ad/NimmetryDI/com/nimmetry/di/LoadListData.py#L34

If the caller never uses the returned value, there is no point in keeping track of a return value in the method, and then returning it. All such code is equivalent to dead code (which means it does not add any value to the program as such)

**Comment by sainimmetry** [comment]
Fixed the issue
