### ISSUE TITLE
Usage of appropriate logging level when printing any log

### ISSUE THREAD

**Issue by suryakiranl** [sainimmetry/PythonDI#8]
https://github.com/sainimmetry/PythonDI/blob/74ef2b80c1f2da4b36e4cbde656382f8979af2ad/NimmetryDI/com/nimmetry/di/LoadListData.py#L40

I notice you have used INFO level as a standard everywhere in the file. For every log statement you write, it is very important to think twice to see what logging level makes sense.

This particular statement should be at DEBUG level, not INFO.

**Comment by sainimmetry** [comment]
Noted and modified for a few lines accordingly.
