### ISSUE TITLE
Code should check if the expected fields exist before accessing data

### ISSUE THREAD

**Issue by suryakiranl** [sainimmetry/PythonDI#9]
https://github.com/sainimmetry/PythonDI/blob/74ef2b80c1f2da4b36e4cbde656382f8979af2ad/NimmetryDI/com/nimmetry/di/LoadListData.py#L46

This code expects valid and successful response from the server. In case when invalid password is provided, the program will fail, instead of existing gracefully. Please think about alternate execution paths as well when writing code.

**Comment by sainimmetry** [comment]
issue fixed and commited
